### ISSUE TITLE
Consider to replace request with other HTTP client since it deprecated

### ISSUE THREAD

**Issue by octet-stream** [PinkiePieIsTheBestPony/ponk-twit-bot#1]
Hello. I just wanted to say that [`request`](https://github.com/request/request) will go to the maintance mode according to [this issue](https://github.com/request/request/issues/3142), so I think it's better to replace it with something else, such as [`node-fetch`](https://github.com/bitinn/node-fetch) which is also lighter than request.
~~And I'm using it in dinky.js btw, so I can definitely recommended this one~~.

You can find more alternatives [here](https://github.com/request/request/issues/3143)

@PinkiePieIsTheBestPony since you're not subscribed to this repository, I call you directly 👋

**Comment by PinkiePieIsTheBestPony** [comment]
Hello Octet, thank you for bring this to my attention! I have decided to go with [node-fetch](https://github.com/bitinn/node-fetch) ~because of your recommendation and usage in dinky.js~

 Changes done in: https://github.com/PinkiePieIsTheBestPony/ponk-twit-bot/pull/2

**Comment by octet-stream** [comment]
Awesome, thanks :)
